### ISSUE TITLE
Review 01

### ISSUE THREAD

**Issue by lukemcd9** [uh-cryptics/zeus#17]
Conduct review in the branch review-17
Files to be reviewed: 
- [x] [ListInventory.jsx](https://github.com/uh-cryptics/zeus/blob/main/app/imports/ui/components/ListInventory.jsx)
- [x] [AddInventory.jsx](https://github.com/uh-cryptics/zeus/blob/main/app/imports/ui/components/AddInventory.jsx)

Checklists:
- [Architecture](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-architecture-checklist)
- [Design](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-design-checklist)
- [Javascript](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-js-checklist)
- [React](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-react-checklist)
- [UI](http://courses.ics.hawaii.edu/ics414f21/morea/review/checklists/reading-ui-checklist)

**Comment by Chase-Lee-ui** [comment]
* AR-01: Obey file name conventions
	Files do not use camel case naming conventions.
* AR-02: Obey directory structure
	Obeys directory structure
* AR-03: Are new directories consistent
	Files are correctly located

* DE-01: Can you refactor
	Can refactor
* DE-02: Avoid deeply nested conditionals
	Barely any neswted conditionals
* DE-03: Eliminate dead code
	All code is used
* DE-04: Eliminate large comment blocks
	No comment blocks
* DE-05: Ensure comments are appropriate
	No comment blocks
* DE-06: Ensure code is readable
	Code is readable
* DE-07: Ensure code is DRY
	Code is DRY
* DE-08: Ensure reusable code is exported
	They are components so they are exported

* JS-01: Name constructs appropriately
	Constructs follow camelCase
* JS-02: Use the spread operator
	No comment
* JS-03: Use object deconstruction
	Do not need object deconstruction
* JS-04: Use arrow functions
	Uses arrow functions
* JS-05: Avoid lodash or underscore .map, .filter, etc
	No lodash
* JS-06: Avoid console.logs
	No console logs
* JS-07: Use JSDoc comments appropriately
	No JSDoc

* ES-01: No errors, avoid warnings
	ListInventory has some eslint errors but does not impact program
* ES-02: Consider modifying our standards
	No comment

* RE-01: Components should be simple
	Components do one thing, add or list
* RE-02: No state updates in loops
	No state updates in loops
* RE-03: Do not rename default exports
	Does not rename default exports
* RE-04: Destructure props in component parameter
	Not used
* RE-06: Define constants in withTracker()
	Once schemas are made can import the JSON data to database but for now not used
* RE-07: Don't retrieve collection data inside render
	Do not
* RE-08: Imported component names and file names should match
	Imported names match
* RE-09: Prefer functions vs. classes
	Uses functions generally
* RE-10: Avoid Widget and Card in names
	Avoids

* TU-01: Each Collection has unit tests
	No unit test
* TI-01: Each Meteor Method has integration tests
	No integration test
* TA-01: Each Page has an isDisplayed acceptance test
	No tests
* TA-02: Each form has an acceptance test
	No tests

**Comment by cammoore** [comment]
## ListInventory.jsx

RE-09: Prefer functions over classes. You can use the 'useState' react
hook.

L31 - 352: Think about creating a separate js file with the
constants. You can now import the constants and use them.

## AddInventory.jsx

RE-09: Prefer functions over classes.

L29 - 63: Use Uniforms

**Comment by rabitz808** [comment]
ListInventory.jsx
L30-L351 DE-08: Reusable code can be exported or made available in the appropriate place.
ES-01: 16 es-lint errors.
UI-07: The console generates errors.

AddInventory.jsx
L17 JS-06: Remove console logs.
L43 ES-01: Es-lint error max line length is 120.
UI-07: The console generates errors.

**Comment by sheenatorres** [comment]
ListInventory.jsx:

AR-02: File located in the appropriate directory

ES-01: Has ES Lint errors

UI-02: Layout not appropriate in smaller screens.

UI-05: Editing the medications/supplies should be with table

UI-07: Console generates errors; Keys are duplicated.


AddInventory.jsx:

ES-01: L42: ES Lint error; Exceeds maximum character length.

UI-07: Console generates errors

**Comment by jktang342** [comment]
ListInventory.jsx
AR-01: Need to use camel case naming conventions.
DE-08: Reusable code can be exported or made available in the appropriate place (L30-L351).
ES-01: Fix ES-lint errors.
UI-07: The console generates errors.
TU-01: Need to create tests.

AddInventory.jsx
AR-01: Need to use camel case naming conventions.
JS-06: Remove console logs (L17).
ES-01: ES-lint error max line length is 120 (L43).
UI-07: The console generates errors.
TU-01: Need to create tests.

**Comment by lukemcd9** [comment]
### ListInventory.jsx
DE-06: The Tables can be made into their own component and pass in the appropriate data as a prop and there are multiple map functions doing somewhat the same thing.
DE-08: The default JSON data can be moved to a JSON file and be imported.
ES-01: There are some ESLint Errors
TU-01: Needs tests

### AddInventory.js
DE-01: Could use Uniforms for the Form
JS-06: Remove console log
TU-01: Needs tests

**Comment by deshay-clemons** [comment]
ListInventory.jsx
DE-08 removing the two object arrays and replacing them with the JSON file
UI-07: The console does generate errors when doing certain actions.
UI-02: The mobile layout is as friendly as viewing it on desktop

AddInventory.jsx
JS-06: Deleting console logs within the file
ES-01: L43: ES Lint of max line error.
